declare module 'react-native-vector-icons/MaterialIcons' {
  import { Icon } from 'react-native-vector-icons/Icon';

  export interface MaterialIconGlyphMap {
    "360": string;
    "3d-rotation": string;
    "ac-unit": string;
    "access-alarm": string;
    "access-alarms": string;
    "access-time": string;
    "accessibility": string;
    "accessible": string;
    "account-balance": string;
    "account-balance-wallet": string;
    "account-box": string;
    "account-circle": string;
    "add": string;
    "add-box": string;
    "add-circle": string;
    "add-circle-outline": string;
    "add-shopping-cart": string;
    "alarm": string;
    "alarm-add": string;
    "alarm-off": string;
    "alarm-on": string;
    "all-inclusive": string;
    "android": string;
    "announcement": string;
    "apps": string;
    "archive": string;
    "arrow-back": string;
    "arrow-downward": string;
    "arrow-drop-down": string;
    "arrow-drop-up": string;
    "arrow-forward": string;
    "arrow-upward": string;
    "assessment": string;
    "assignment": string;
    "assignment-ind": string;
    "assignment-late": string;
    "assignment-return": string;
    "assignment-returned": string;
    "assignment-turned-in": string;
    "attach-file": string;
    "attach-money": string;
    "autorenew": string;
    "backspace": string;
    "backup": string;
    "battery-alert": string;
    "battery-charging-full": string;
    "battery-full": string;
    "battery-std": string;
    "battery-unknown": string;
    "beach-access": string;
    "beenhere": string;
    "block": string;
    "bluetooth": string;
    "bluetooth-searching": string;
    "bluetooth-connected": string;
    "bluetooth-disabled": string;
    "blur-circular": string;
    "blur-linear": string;
    "blur-off": string;
    "blur-on": string;
    "book": string;
    "bookmark": string;
    "bookmark-border": string;
    "border-all": string;
    "border-bottom": string;
    "border-clear": string;
    "border-color": string;
    "border-horizontal": string;
    "border-inner": string;
    "border-left": string;
    "border-outer": string;
    "border-right": string;
    "border-style": string;
    "border-top": string;
    "border-vertical": string;
    "branding-watermark": string;
    "brightness-1": string;
    "brightness-2": string;
    "brightness-3": string;
    "brightness-4": string;
    "brightness-5": string;
    "brightness-6": string;
    "brightness-7": string;
    // ... adicione mais conforme necessário
  }

  export const glyphMap: MaterialIconGlyphMap;
  const MaterialIcons: Icon<keyof MaterialIconGlyphMap>;
  export default MaterialIcons;
}
