export type RootStackParamList = {
    Home: undefined;
    Login: undefined;
    Register: undefined;
    Dashboard: undefined;
    Settings: undefined;
    Refresh: undefined;
    Logout: undefined;
    Chat: undefined;
    Compras: undefined;
    Vendas: undefined;
    Estoque: undefined;
    Financeiro: undefined;
    Relatorios: undefined;
    Gestor: undefined;
    NewShop: undefined;
    HistoryShop: undefined;
    NewSale: undefined;
    HistorySale: undefined;
    Invoice: undefined;
};