export type RootStackParamList = {
    Home: undefined;
    Login: undefined;
    Register: undefined;
    Dashboard: undefined;
    Settings: undefined;
    Refresh: undefined;
    Logout: undefined;
    Chat: undefined;
    Compras: undefined;
    Vendas: undefined;
    Estoque: undefined;
    Financeiro: undefined;
    Relatorios: undefined;
    Gestor: undefined;
    NewShop: undefined;
    HistoryShop: undefined;
    NewSale: undefined;
    HistorySale: undefined;
    Invoice: undefined;
    RegisterProduct: undefined;
    RegisterCustomers: undefined;
    NewCustomers: undefined;
    EditCustomers: undefined;
    NewProduct: undefined;
    EditProduct: undefined;
    RegisterSuppliers: undefined;
    NewSuppliers: undefined;
    EditSuppliers: undefined;
    RegisterPaymentMethods: undefined;
    NewPaymentMethods: undefined;
    EditPaymentMethods: undefined;
    RegisterCategories: undefined;
    NewCategory: undefined;
    EditCategory: undefined; 
    
};